// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user.proto

#ifndef PROTOBUF_INCLUDED_proto_2fuser_2eproto
#define PROTOBUF_INCLUDED_proto_2fuser_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_proto_2fuser_2eproto 

namespace protobuf_proto_2fuser_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_proto_2fuser_2eproto
namespace User {
class UserInfo;
class UserInfoDefaultTypeInternal;
extern UserInfoDefaultTypeInternal _UserInfo_default_instance_;
}  // namespace User
namespace google {
namespace protobuf {
template<> ::User::UserInfo* Arena::CreateMaybeMessage<::User::UserInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace User {

enum UserInfo_Job {
  UserInfo_Job_TEACHER = 0,
  UserInfo_Job_DOCTOR = 1,
  UserInfo_Job_POLICE = 2,
  UserInfo_Job_UserInfo_Job_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  UserInfo_Job_UserInfo_Job_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool UserInfo_Job_IsValid(int value);
const UserInfo_Job UserInfo_Job_Job_MIN = UserInfo_Job_TEACHER;
const UserInfo_Job UserInfo_Job_Job_MAX = UserInfo_Job_POLICE;
const int UserInfo_Job_Job_ARRAYSIZE = UserInfo_Job_Job_MAX + 1;

const ::google::protobuf::EnumDescriptor* UserInfo_Job_descriptor();
inline const ::std::string& UserInfo_Job_Name(UserInfo_Job value) {
  return ::google::protobuf::internal::NameOfEnum(
    UserInfo_Job_descriptor(), value);
}
inline bool UserInfo_Job_Parse(
    const ::std::string& name, UserInfo_Job* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UserInfo_Job>(
    UserInfo_Job_descriptor(), name, value);
}
// ===================================================================

class UserInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:User.UserInfo) */ {
 public:
  UserInfo();
  virtual ~UserInfo();

  UserInfo(const UserInfo& from);

  inline UserInfo& operator=(const UserInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UserInfo(UserInfo&& from) noexcept
    : UserInfo() {
    *this = ::std::move(from);
  }

  inline UserInfo& operator=(UserInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserInfo* internal_default_instance() {
    return reinterpret_cast<const UserInfo*>(
               &_UserInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(UserInfo* other);
  friend void swap(UserInfo& a, UserInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UserInfo* New() const final {
    return CreateMaybeMessage<UserInfo>(NULL);
  }

  UserInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UserInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UserInfo& from);
  void MergeFrom(const UserInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef UserInfo_Job Job;
  static const Job TEACHER =
    UserInfo_Job_TEACHER;
  static const Job DOCTOR =
    UserInfo_Job_DOCTOR;
  static const Job POLICE =
    UserInfo_Job_POLICE;
  static inline bool Job_IsValid(int value) {
    return UserInfo_Job_IsValid(value);
  }
  static const Job Job_MIN =
    UserInfo_Job_Job_MIN;
  static const Job Job_MAX =
    UserInfo_Job_Job_MAX;
  static const int Job_ARRAYSIZE =
    UserInfo_Job_Job_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Job_descriptor() {
    return UserInfo_Job_descriptor();
  }
  static inline const ::std::string& Job_Name(Job value) {
    return UserInfo_Job_Name(value);
  }
  static inline bool Job_Parse(const ::std::string& name,
      Job* value) {
    return UserInfo_Job_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string name = 3;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // int32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // int32 age = 2;
  void clear_age();
  static const int kAgeFieldNumber = 2;
  ::google::protobuf::int32 age() const;
  void set_age(::google::protobuf::int32 value);

  // .User.UserInfo.Job job = 4;
  void clear_job();
  static const int kJobFieldNumber = 4;
  ::User::UserInfo_Job job() const;
  void set_job(::User::UserInfo_Job value);

  // @@protoc_insertion_point(class_scope:User.UserInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 uid_;
  ::google::protobuf::int32 age_;
  int job_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_proto_2fuser_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UserInfo

// int32 uid = 1;
inline void UserInfo::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 UserInfo::uid() const {
  // @@protoc_insertion_point(field_get:User.UserInfo.uid)
  return uid_;
}
inline void UserInfo::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:User.UserInfo.uid)
}

// int32 age = 2;
inline void UserInfo::clear_age() {
  age_ = 0;
}
inline ::google::protobuf::int32 UserInfo::age() const {
  // @@protoc_insertion_point(field_get:User.UserInfo.age)
  return age_;
}
inline void UserInfo::set_age(::google::protobuf::int32 value) {
  
  age_ = value;
  // @@protoc_insertion_point(field_set:User.UserInfo.age)
}

// string name = 3;
inline void UserInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserInfo::name() const {
  // @@protoc_insertion_point(field_get:User.UserInfo.name)
  return name_.GetNoArena();
}
inline void UserInfo::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:User.UserInfo.name)
}
#if LANG_CXX11
inline void UserInfo::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:User.UserInfo.name)
}
#endif
inline void UserInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:User.UserInfo.name)
}
inline void UserInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:User.UserInfo.name)
}
inline ::std::string* UserInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:User.UserInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserInfo::release_name() {
  // @@protoc_insertion_point(field_release:User.UserInfo.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:User.UserInfo.name)
}

// .User.UserInfo.Job job = 4;
inline void UserInfo::clear_job() {
  job_ = 0;
}
inline ::User::UserInfo_Job UserInfo::job() const {
  // @@protoc_insertion_point(field_get:User.UserInfo.job)
  return static_cast< ::User::UserInfo_Job >(job_);
}
inline void UserInfo::set_job(::User::UserInfo_Job value) {
  
  job_ = value;
  // @@protoc_insertion_point(field_set:User.UserInfo.job)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace User

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::User::UserInfo_Job> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::User::UserInfo_Job>() {
  return ::User::UserInfo_Job_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_proto_2fuser_2eproto
